### ISSUE TITLE
KinectTransport does not appear to be Saving/Restoring previous settings

### ISSUE THREAD

**Issue by joelpryde** [stimulant/MS-Cube-SDK#10]
The KinectTransport does not appear to be saving/restoring previous settings; We find we have to manually check the Enabled and Bodies Enabled and Depth Enabled checkboxes every time KinectTransport starts up.  (Perhaps it only attempts to save these if “Start Kinect Transport on Startup” is checked, or perhaps this is this working in general but not in our environment?)

**Comment by joelpryde** [comment]
Are you still seeing this?  Can you check the values in HKEY_CURRENT_USER\Software\KinectTransport in regedit and see if they are changing?  It could be a permissions issue but these are definitely getting saved/loaded correctly for me.

**Comment by dr-ratio** [comment]
Ah, after looking at the registry, and stepping through some code:  it appears that data is getting saved and restored correctly.  So the real bug here is that the UI does not reflect it.  For example, after I watched fSendBodiesData[0] be set to true, I F5 continued execution, opened the settings dialog, and the checkbox was not checked to match that internal data.
